services:
  web:
    build: .
    image: it-solution-app:1.0
    container_name: it-solution-container
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: itsolutiondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: